# Nome do workflow que aparece na aba "Actions"
name: Mensagem de Boas-Vindas

# O workflow ser치 executado sempre que houver um push no reposit칩rio
on: [push]

jobs:
  # Definindo um job chamado "mensagem"
  mensagem:
    # O job ser치 executado em uma m치quina virtual com Ubuntu 
    runs-on: ubuntu-latest

    # Lista de etapas (steps) que esse job vai executar
    steps:
      # Step 칰nico que executa comandos de terminal
      - run: |
          # Imprime uma mensagem de boas-vindas nos logs do workflow
          echo "游 Bem-vindo ao GitHub Actions!"

          # Imprime a data e hora atual 
          echo "游 Data e hora: $(date)"

          # Imprime o nome do usu치rio que fez o push 
          echo "游녻 Usu치rio:$GITHUB_ACTOR"
